### ISSUE TITLE
NaN err for LinearMixedModel with rank deficient Fixed-effects matrix  

### ISSUE THREAD

**Issue by PharmCat** [beacon-biosignals/Effects.jl#62]
So...

I got NaN for err

![image](https://github.com/beacon-biosignals/Effects.jl/assets/13901158/054c63fa-e298-493a-b2fd-7eb243713508)

I used LinearMixedModel from MixedModels.jl and Fixed-effects matrix is rank deficient

**Comment by ararslan** [comment]
I just ran into this as well. It's because of https://github.com/beacon-biosignals/Effects.jl/blob/f5e13ad0edab70605564a5897e9999f8a98669eb/src/regressionmodel.jl#L128
For a rank deficient mixed model, `vcov` will have rows/columns of `NaN`s for the terms that were dropped. Multiplying this by the model matrix as is done there results in a matrix of just `NaN`s.

It sounds like @palday will be looking into a proper fix to support rank deficient models but in the meantime this seems to work and I _think_ does the right thing:
```julia
using DataFrames, Effects, LinearAlgebra, MixedModels
# Miscellaneous internals needed for the method definition
using Effects: modelcols, typify, _difference_method!, _responsename
using MixedModels: feL

function Effects.effects!(reference_grid::DataFrame, model::MixedModel;
                          eff_col=nothing, err_col=:err, typical=mean, invlink=identity,
                          vcov=vcov)
    form = formula(model)
    form_typical = typify(reference_grid, form, modelmatrix(model); typical=typical)
    X = modelcols(form_typical, reference_grid)
    eff = X * coef(model)
    r = rank(model)
    if r == size(modelmatrix(model), 2)
        Σ = vcov(model)
    else
        X = X[:, model.feterm.piv[1:r]]
        Linv = inv(feL(model))
        Σ = Linv'Linv
        Σ .*= dispersion(model, true)
    end
    err = sqrt.(diag(X * Σ * X'))
    _difference_method!(eff, err, model, invlink)
    reference_grid[!, something(eff_col, _responsename(model))] = eff
    reference_grid[!, err_col] = err
    return reference_grid
end
```
This defines a more specific method than what would otherwise be called.
